name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        source-url:  https://thefoschinigroup.pkgs.visualstudio.com/_packaging/TFG/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: B821B22F-6E3A-449B-A4E3-504A7085556D 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
